default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: <?= databaseName ?>_development

test:
  <<: *default
  database: <?= databaseName ?>_test

production:
  <<: *default
  database: production
  username: <%= ENV['PG_USER'] %>
  password: <%= ENV['PG_PASS'] %>
